<?php

if (Mage::helper('facebookchat/data')->isEnable()) {

    $appId = Mage::helper('facebookchat/data')->getAppId();
    $pageId = Mage::helper('facebookchat/data')->getPageId();
    $color = '#'.Mage::helper('facebookchat/data')->geThemeColor();
    $loginText = Mage::helper('facebookchat/data')->getLoginText();
    $logoutText = Mage::helper('facebookchat/data')->getLogoutText();

    if (empty($loginText)) {
        $loginText = 'Hi! What can i Help you?';
    }
    if (empty($logoutText)) {
        $logoutText = 'Hi! What can i Help you?';
    }
    ?>
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
            FB.init({
                appId            : '<?php echo $appId;?>',
                autoLogAppEvents : true,
                xfbml            : true,
                version          : 'v3.2'
            });
        };

        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="fb-customerchat"
         attribution=setup_tool
         page_id="<?php echo $pageId; ?>"
         theme_color="<?php echo $color; ?>"
         logged_in_greeting="<?php echo $loginText; ?>"
         logged_out_greeting="<?php echo $logoutText; ?>">
    </div>
    <?php
}
?>